### ISSUE TITLE
Ability to link to session from mobile applications

### ISSUE THREAD

**Issue by chrissearle** [javaBin/javazone-2020#30]
Am assuming that the "programme" pages will be implemented under this project :)

iOS and android provide standard ways to offer the user a "share this" function. For us the best thing would be a link to the session on the web (pretty much the only real meaningful thing to share).

If that is to work then we need to be able to have a direct link to the "show this session" page (so - it needs to be something the web server considers a page with its own URL).

In addition - we need to be able to construct the URL based on the data we have. Several options here - but they end up being "a known prefix" and "a known data field". We have the data from sleepingpill so sessionId seems like a nice choice.

* https://2020.javazone.no/<sessionId>
* https://2020.javazone.no/sessions/<sessionId>

If this could be taken into consideration when building the program section I'd appreciate it :)

**Comment by alexander-svendsen** [comment]
Like the previous years? 
https://2019.javazone.no/program/367f96cb-81f2-49e4-a143-97a8dcb8d220
https://2018.javazone.no/program/39a8f7b1-e0a4-40f2-a684-ff58ecd163db

**Comment by chrissearle** [comment]
Sure - if you’re keeping the same site structure this year then that’s fine.

**Comment by alexander-svendsen** [comment]
Thats the plan :)

**Comment by chrissearle** [comment]
Excellent. That means I can implement. Have added https://github.com/javaBin/sleepingPillCore/issues/27 to get the correct prefix - but for the web project - sounds like this is OK :)
